### ISSUE TITLE
无法修改配置，提示serializeJSON is not a function

### ISSUE THREAD

**Issue by UserB1ank** [frankli0324/ctfd-whale#18]
<img width="538" alt="image" src="https://github.com/frankli0324/ctfd-whale/assets/105202277/09c0b2b4-9e55-405e-bbd6-012e1f2d63a1">

**Comment by UserB1ank** [comment]
当前项目asset下的config.js无法识别serilizeJSON，看上去是import出了问题。CTFd3.7应该修改了部分js函数的位置。我把版本回退到3.6就正常了

**Comment by frankli0324** [comment]
CTFd侧应当已经解决了，重新clone一下CTFd试试

**Comment by UserB1ank** [comment]
ok&nbsp;


2577110290
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月4日(星期一) 晚上6:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [frankli0324/ctfd-whale] 无法修改配置，提示serializeJSON is not a function (Issue #18)





 
CTFd侧应当已经解决了，重新clone一下CTFd试试
