### ISSUE TITLE
Wrong configuration in admin panel leads to internal server errors

### ISSUE THREAD

**Issue by ne-bknn** [frankli0324/ctfd-whale#4]
**Problem**: Setting, for example, `docker socket` to something unavailable, or `http domain suffix` to empty string leads to internal errors in whale settings page. Fixing such an installation requires hardcoding values in source code or manually modifying them in database. 

**Expected behavior**: Setting wrong value is impossible or does not lead to admin page crash.

**Comment by frankli0324** [comment]
this is WIERD.
I remembered that I resolved this issue weeks ago, yet I can't find ANY clue indicating that.
I could remember nearly every detail implementing checks on config items, but I can't find it ANYWHERE.
WHAT HAPPENED

**Comment by frankli0324** [comment]
resolved with
181a003e77
06c4847352
