### ISSUE TITLE
无法renew容器

### ISSUE THREAD

**Issue by a1oyss** [frankli0324/ctfd-whale#6]
正常功能下是会带有一个chanllage_id
`DELETE /api/v1/plugins/ctfd-whale/container?challenge_id=1`
而renew的是没有的
`PATCH /api/v1/plugins/ctfd-whale/container`

管理员权限和普通用户权限下都无法成功renew

**Comment by frankli0324** [comment]
按理来说renew本身是用不着challenge_id参数的，只是检查题目是否向选手可见时会用到此参数
请确认一下题目是否visible？
当然，会加上的，火车上不方便

**Comment by a1oyss** [comment]
> 由于当前这个插件只允许一个用户开一个容器，所以按理来说renew本身是用不着challenge_id参数的，只是检查题目是否向选手可见时会用到此参数，所以本来就没给renew加这个参数
> 请确认一下题目是否visible？
> 当然，由于管理员调试题目不方便，而且考虑到同步buu一个用户开多个容器的功能，会加上challenge_id参数的

visible状态也一样，报错：
`no such challenge. You have requested this URI [/api/v1/plugins/ctfd-whale/container] but did you mean /api/v1/plugins/ctfd-whale/container or /api/v1/plugins/ctfd-whale/admin/container or /plugins/ctfd-whale/admin/containers ?`

**Comment by frankli0324** [comment]
fixed
